server:
  port: 8081

ftp:
  host: 192.168.2.2
  port: 21
  username: root
  password: 123456
  mode: Passive
  remotePath: /root/export/
  localPath: /Users/simonxue/Developer/Temp/
template:
  employee: employee.xlsx
